SELECT @@SERVERNAME;

--CREATING
CREATE DATABASE CustomerSupportDB;

--CHECK TABLE NAME
SELECT TABLE_NAME 
FROM INFORMATION_SCHEMA.TABLES;

--TESTING
USE CustomerSupportDB;

SELECT * FROM customer_data;

-- ***************** QUERIES ********************

--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) AS revenue
FROM Customer_data
GROUP BY gender;


--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT customer_id, purchase_amount
FROM Customer_data
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM Customer_data);


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating), 2) AS Avg_rating
FROM Customer_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, AVG(purchase_amount) AS Average_Amount
FROM Customer_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT subscription_status, 
       COUNT(customer_id) AS Total_Emp, 
       AVG(purchase_amount) AS Avg_Spend, 
       SUM(purchase_amount) AS Total_Revenue
FROM Customer_data
GROUP BY subscription_status
ORDER BY Total_Revenue, Avg_Spend DESC;


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5 item_purchased,
       CAST(
           ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
           / COUNT(*), 2)
       AS DECIMAL(5,2)) AS discount_rate
FROM Customer_data
GROUP BY item_purchased
ORDER BY discount_rate DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
    SELECT customer_id, previous_purchases,
    CASE
        WHEN previous_purchases = 1 THEN 'New'
        WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment
FROM Customer_data)

SELECT customer_segment, COUNT(*) AS 'Number Of Customer'
FROM customer_type
GROUP BY customer_segment
ORDER BY 'Number Of Customer';


--Q8. What are the top 3 most purchased products within each category? 
WITH item_count AS (
    SELECT category,
            item_purchased,
            COUNT(customer_id) AS Total_orders,
            ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS rnk
    FROM Customer_data
    GROUP BY category, item_purchased)

SELECT rnk, category, item_purchased, total_orders
FROM item_count
WHERE rnk <= 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT *
FROM (
    SELECT customer_id, previous_purchases, subscription_status,
        CASE
            WHEN previous_purchases > 5 THEN 'Repeated Buyers'
            ELSE 'Non Repeated Buyers'
        END AS Buyers
    FROM Customer_Data
) t
WHERE Buyers = 'Repeated Buyers'
  AND subscription_status = 'Yes';
------------------------------------------------------------------
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM Customer_data
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT age_group AS 'Age Group', SUM(purchase_amount) AS 'Revenue Contribution'
FROM Customer_Data
GROUP BY age_group
ORDER BY SUM(purchase_amount);